version: 2.1
jobs:
  deploy:
    working_directory: ~/dockerfiles
    docker:
      - image: docker:18.09.6-git
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --update make
      - run: echo "${DOCKERHUB_PASS}" >> .dockerhub_pass
      - run: make push

workflows:
  version: 2
  
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
  
      